# Generated by Django 3.2.16 on 2022-12-27 22:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя тега')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Описание фотографии')),
                ('img', models.ImageField(height_field='img_height', upload_to='', verbose_name='Фотография', width_field='img_width')),
                ('img_height', models.IntegerField(default=0, editable=False)),
                ('img_width', models.IntegerField(default=0, editable=False)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата добавления')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_photo', to='album.album', verbose_name='Альбом')),
                ('tags', models.ManyToManyField(blank=True, related_name='photo_tag', to='album.Tag', verbose_name='Список тегов')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'ordering': ('-added_at',),
            },
        ),
    ]
